apiVersion: "kubeflow.org/v1"
kind: TFJob
metadata:
  name: anomalytrain
  namespace: kubeflow-user-example-com
spec:
   runPolicy:
     cleanPodPolicy: None
   tfReplicaSpecs:
     Worker:
       replicas: 3
       restartPolicy: OnFailure
       template:
         metadata:
           annotations:
             sidecar.istio.io/inject: "false"
         spec:
           containers:
             - name: tensorflow
               image: johnugeorge/anomalytrain:1.0
               command:
                 - "python"
                 - "/opt/anomalytrain.py"
                 - "--logsdir"
                 - "/mnt/vol"
               #resources:
               #  limits:
               #    nvidia.com/gpu: 2
